"""add file_objects table (fix)

Revision ID: c7825a31fe81
Revises: f36355c3df41
Create Date: 2026-01-06 15:01:09.532303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7825a31fe81'
down_revision: Union[str, None] = 'f36355c3df41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_objects'))
    )
    op.create_index(op.f('ix_file_objects_owner_id'), 'file_objects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_file_objects_storage_key'), 'file_objects', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_objects_storage_key'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_owner_id'), table_name='file_objects')
    op.drop_table('file_objects')
    # ### end Alembic commands ###

